/****************** main.c for model {{ model_uuid }} generated by nn-loader.py *******************/
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/version.h>
#include <linux/slab.h>

#include "linux/liteflow.h"

{% for layer_id in range(0, layer_list|length) %}
/************************************** Layer {{ layer_id }} **************************************/
{{ layer_list[layer_id].generate_comp_code(layer_id) }}

{{ layer_list[layer_id].generate_struct_code(layer_id) }}
/************************************ End Layer {{ layer_id }} ************************************/
{% endfor %}

/************************************** Model {{ model_id }} **************************************/

struct model_container model_{{ model_uuid }} __read_mostly = {
    .uuid = {{ model_uuid }},
    .input_size = {{ input_size }},
    .output_size = {{ output_size }},
};

static int
__init liteflow_{{ model_uuid }}_model_init(void)
{
    lf_register_model({{ app_id }}, &model_{{ model_uuid }});

    // Construct
    INIT_LIST_HEAD(&model_{{ model_uuid }}.layers);
    {% for layer_id in range(0, layer_list|length) %}
    {%- if loop.first -%}
    list_add(&layer_{{ layer_id }}.list, &model_{{ model_uuid }}.layers);
    {%- else %}
    list_add(&layer_{{ layer_id }}.list, &layer_{{ layer_id - 1}}.list);
    {%- endif -%}
    {% endfor %}
    
    return 0;
}

static void
__exit liteflow_{{ model_uuid }}_model_exit(void)
{
    lf_unregister_model({{ app_id}}, {{ model_uuid }});
}

module_init(liteflow_{{ model_uuid }}_model_init);
module_exit(liteflow_{{ model_uuid }}_model_exit);

MODULE_DESCRIPTION("liteflow {{ model_uuid }} model");
MODULE_AUTHOR("Junxue ZHANG");
MODULE_LICENSE("GPL v2");

/************************************ End Model {{ model_id }} ************************************/
