// The sample model code can be generated by configurator outside datapath

#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/version.h>
#include <linux/slab.h>

#include "linux/liteflow.h"

struct app app1 = {
    .appid = 1,
    .input_size = 8,
    .output_size = 8,
};

struct app app2 = {
    .appid = 2,
    .input_size = 8,
    .output_size = 8,
};

struct app app3 = {
    .appid = 67,
    .input_size = 8,
    .output_size = 8,
};

static int
__init liteflow_sample_model_init(void)
{
    lf_register_app(&app1);
    lf_register_app(&app2);
    lf_register_app(&app1);
    lf_register_app(&app3);
    return 0;
}

static void
__exit liteflow_sample_model_exit(void)
{
    lf_unregister_app(1);
    lf_unregister_app(2);
    lf_unregister_app(5);
    lf_unregister_app(1);
}

module_init(liteflow_sample_model_init);
module_exit(liteflow_sample_model_exit);

MODULE_DESCRIPTION("liteflow sample model");
MODULE_AUTHOR("Junxue ZHANG");
MODULE_LICENSE("GPL");