/****************** main.c for model 2333 generated by nn-loader.py *******************/
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/version.h>
#include <linux/slab.h>

#include "linux/liteflow.h"


/************************************** Layer 0 **************************************/
static void quan_0_comp (s64 *input, s64 *output)
{
    // Q_min: 0.0
    // Q_max: 62.0
    
    output[0] = (input[0] - 0) * 255 / 62 + -128;    
    printk(KERN_INFO "Output_quan_0_%d: %lld", 0, output[0]);
    
    
    output[1] = (input[1] - 0) * 255 / 62 + -128;    
    printk(KERN_INFO "Output_quan_0_%d: %lld", 1, output[1]);
    
    
    output[2] = (input[2] - 0) * 255 / 62 + -128;    
    printk(KERN_INFO "Output_quan_0_%d: %lld", 2, output[2]);
    
    
    output[3] = (input[3] - 0) * 255 / 62 + -128;    
    printk(KERN_INFO "Output_quan_0_%d: %lld", 3, output[3]);
    
    
}

struct model_layer layer_0 __read_mostly = {
    .uuid = 0,
    .input_size = 4,
    .output_size = 4,
    .comp_func = quan_0_comp,
};
/************************************ End Layer 0 ************************************/

/************************************** Layer 1 **************************************/
static void fc_1_comp (s64 *input, s64 *output)
{
    
    output[0] =(input[0] + 128) * (-13 + 0) + (input[1] + 128) * (9 + 0) + (input[2] + 128) * (19 + 0) + (input[3] + 128) * (-31 + 0) + (-113);
    output[0] = output[0] * 8896 / 1000000 + 24;
    printk(KERN_INFO "Output_fc_1_%d: %lld", 0, output[0]);

    
    output[1] =(input[0] + 128) * (-8 + 0) + (input[1] + 128) * (12 + 0) + (input[2] + 128) * (8 + 0) + (input[3] + 128) * (-39 + 0) + (172);
    output[1] = output[1] * 8896 / 1000000 + 24;
    printk(KERN_INFO "Output_fc_1_%d: %lld", 1, output[1]);

    
    output[2] =(input[0] + 128) * (-38 + 0) + (input[1] + 128) * (-22 + 0) + (input[2] + 128) * (49 + 0) + (input[3] + 128) * (-49 + 0) + (236);
    output[2] = output[2] * 8896 / 1000000 + 24;
    printk(KERN_INFO "Output_fc_1_%d: %lld", 2, output[2]);

    
    output[3] =(input[0] + 128) * (-12 + 0) + (input[1] + 128) * (32 + 0) + (input[2] + 128) * (-8 + 0) + (input[3] + 128) * (11 + 0) + (147);
    output[3] = output[3] * 8896 / 1000000 + 24;
    printk(KERN_INFO "Output_fc_1_%d: %lld", 3, output[3]);

    
    output[4] =(input[0] + 128) * (-127 + 0) + (input[1] + 128) * (2 + 0) + (input[2] + 128) * (21 + 0) + (input[3] + 128) * (-9 + 0) + (962);
    output[4] = output[4] * 8896 / 1000000 + 24;
    printk(KERN_INFO "Output_fc_1_%d: %lld", 4, output[4]);

    
    output[5] =(input[0] + 128) * (-1 + 0) + (input[1] + 128) * (-3 + 0) + (input[2] + 128) * (46 + 0) + (input[3] + 128) * (3 + 0) + (396);
    output[5] = output[5] * 8896 / 1000000 + 24;
    printk(KERN_INFO "Output_fc_1_%d: %lld", 5, output[5]);

    
    output[6] =(input[0] + 128) * (-42 + 0) + (input[1] + 128) * (-22 + 0) + (input[2] + 128) * (-20 + 0) + (input[3] + 128) * (6 + 0) + (198);
    output[6] = output[6] * 8896 / 1000000 + 24;
    printk(KERN_INFO "Output_fc_1_%d: %lld", 6, output[6]);

    
    output[7] =(input[0] + 128) * (15 + 0) + (input[1] + 128) * (-5 + 0) + (input[2] + 128) * (-55 + 0) + (input[3] + 128) * (27 + 0) + (-357);
    output[7] = output[7] * 8896 / 1000000 + 24;
    printk(KERN_INFO "Output_fc_1_%d: %lld", 7, output[7]);

    
}

struct model_layer layer_1 __read_mostly = {
    .uuid = 1,
    .input_size = 4,
    .output_size = 8,
    .comp_func = fc_1_comp,
};
/************************************ End Layer 1 ************************************/

/************************************** Layer 2 **************************************/
static void fc_2_comp (s64 *input, s64 *output)
{
    
    output[0] =(input[0] + -24) * (31 + 0) + (input[1] + -24) * (-75 + 0) + (input[2] + -24) * (-127 + 0) + (input[3] + -24) * (-114 + 0) + (input[4] + -24) * (-24 + 0) + (input[5] + -24) * (-21 + 0) + (input[6] + -24) * (-48 + 0) + (input[7] + -24) * (97 + 0) + (-253);
    output[0] = output[0] * 20483 / 1000000 + -128;
    printk(KERN_INFO "Output_fc_2_%d: %lld", 0, output[0]);

    
}

struct model_layer layer_2 __read_mostly = {
    .uuid = 2,
    .input_size = 8,
    .output_size = 1,
    .comp_func = fc_2_comp,
};
/************************************ End Layer 2 ************************************/

/************************************** Layer 3 **************************************/
static void dequan_3_comp (s64 *input, s64 *output)
{
    // Q_min: 0.0
    // Q_max: 30.02955436706543
    
    output[0] = (input[0] + 128) * 30 / 255 + 0;
    
}

struct model_layer layer_3 __read_mostly = {
    .uuid = 3,
    .input_size = 1,
    .output_size = 1,
    .comp_func = dequan_3_comp,
};
/************************************ End Layer 3 ************************************/


/************************************** Model  **************************************/

struct model_container model_2333 __read_mostly = {
    .uuid = 2333,
    .input_size = 4,
    .output_size = 1,
};


/******************************************** Test Mode ********************************************/
struct app app = {
    .appid = 1,
    .input_size = 4,
    .output_size = 1,
};

/**************************************** End Test Mode ********************************************/


static int
__init liteflow_2333_model_init(void)
{
    
    s64 _input[4];
    s64 _output[1];
    int _output_pos;
    

    // Construct layers
    INIT_LIST_HEAD(&model_2333.layers);
    list_add(&layer_0.list, &model_2333.layers);
    list_add(&layer_1.list, &layer_0.list);
    list_add(&layer_2.list, &layer_1.list);
    list_add(&layer_3.list, &layer_2.list);

    
    // Test mode = on
    lf_register_app(&app);
    
    
    lf_register_model(1, &model_2333);

    
    lf_activate_model(1, 2333);
    
    // TODO
    _input[0] = 11 ;
    _input[1] = 31 ;
    _input[2] = 21 ;
    _input[3] = 41 ;

    lf_query_model(1, _input, _output);

    for (_output_pos = 0; _output_pos < 1; ++_output_pos) {
        printk(KERN_INFO "Output_%d: %lld\n", _output_pos, _output[_output_pos]);
    }
    

    return 0;
}

static void
__exit liteflow_2333_model_exit(void)
{
    lf_unregister_model(1, 2333);

    
    // Test mode = on
    lf_unregister_app(1);
    
}

module_init(liteflow_2333_model_init);
module_exit(liteflow_2333_model_exit);

MODULE_DESCRIPTION("liteflow 2333 model");
MODULE_AUTHOR("liteflow");
MODULE_LICENSE("GPL v2");

/************************************ End Model  ************************************/