/****************** main.c for model 2333 generated by nn-loader.py *******************/
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/version.h>
#include <linux/slab.h>

#include "linux/liteflow.h"


/************************************** Layer 0 **************************************/
static void quan_0_comp (s64 *input, s64 *output)
{
    // Q_min: 0.0
    // Q_max: 62.0
    
    output[0] = (input[0] - 0) * 255 / (62 - 0) - 128;
    // if (output[0] > 127) {
    //     output[0] = 127;
    // }
    // if (output[0] < -128) {
    //     output[0] = -128;
    // }
    
    output[1] = (input[1] - 0) * 255 / (62 - 0) - 128;
    // if (output[1] > 127) {
    //     output[1] = 127;
    // }
    // if (output[1] < -128) {
    //     output[1] = -128;
    // }
    
    output[2] = (input[2] - 0) * 255 / (62 - 0) - 128;
    // if (output[2] > 127) {
    //     output[2] = 127;
    // }
    // if (output[2] < -128) {
    //     output[2] = -128;
    // }
    
    output[3] = (input[3] - 0) * 255 / (62 - 0) - 128;
    // if (output[3] > 127) {
    //     output[3] = 127;
    // }
    // if (output[3] < -128) {
    //     output[3] = -128;
    // }
    
}

struct model_layer layer_0 __read_mostly = {
    .uuid = 0,
    .input_size = 4,
    .output_size = 4,
    .comp_func = quan_0_comp,
};
/************************************ End Layer 0 ************************************/

/************************************** Layer 1 **************************************/
static void fc_1_comp (s64 *input, s64 *output)
{
    
    output[0] =input[0] * -13 + input[1] * 9 + input[2] * 19 + input[3] * -31+  -113;
    // if (output[0] > 127) {
    //     output[0] = 127;
    // }
    // if (output[0] < -128) {
    //     output[0] = -128;
    // }
    
    output[1] =input[0] * -8 + input[1] * 12 + input[2] * 8 + input[3] * -39+  172;
    // if (output[1] > 127) {
    //     output[1] = 127;
    // }
    // if (output[1] < -128) {
    //     output[1] = -128;
    // }
    
    output[2] =input[0] * -38 + input[1] * -22 + input[2] * 49 + input[3] * -49+  236;
    // if (output[2] > 127) {
    //     output[2] = 127;
    // }
    // if (output[2] < -128) {
    //     output[2] = -128;
    // }
    
    output[3] =input[0] * -12 + input[1] * 32 + input[2] * -8 + input[3] * 11+  147;
    // if (output[3] > 127) {
    //     output[3] = 127;
    // }
    // if (output[3] < -128) {
    //     output[3] = -128;
    // }
    
    output[4] =input[0] * -127 + input[1] * 2 + input[2] * 21 + input[3] * -9+  962;
    // if (output[4] > 127) {
    //     output[4] = 127;
    // }
    // if (output[4] < -128) {
    //     output[4] = -128;
    // }
    
    output[5] =input[0] * -1 + input[1] * -3 + input[2] * 46 + input[3] * 3+  396;
    // if (output[5] > 127) {
    //     output[5] = 127;
    // }
    // if (output[5] < -128) {
    //     output[5] = -128;
    // }
    
    output[6] =input[0] * -42 + input[1] * -22 + input[2] * -20 + input[3] * 6+  198;
    // if (output[6] > 127) {
    //     output[6] = 127;
    // }
    // if (output[6] < -128) {
    //     output[6] = -128;
    // }
    
    output[7] =input[0] * 15 + input[1] * -5 + input[2] * -55 + input[3] * 27+  -357;
    // if (output[7] > 127) {
    //     output[7] = 127;
    // }
    // if (output[7] < -128) {
    //     output[7] = -128;
    // }
    
}

struct model_layer layer_1 __read_mostly = {
    .uuid = 1,
    .input_size = 4,
    .output_size = 8,
    .comp_func = fc_1_comp,
};
/************************************ End Layer 1 ************************************/

/************************************** Layer 2 **************************************/
static void fc_2_comp (s64 *input, s64 *output)
{
    
    output[0] =input[0] * 31 + input[1] * -75 + input[2] * -127 + input[3] * -114 + input[4] * -24 + input[5] * -21 + input[6] * -48 + input[7] * 97+  -253;
    // if (output[0] > 127) {
    //     output[0] = 127;
    // }
    // if (output[0] < -128) {
    //     output[0] = -128;
    // }
    
}

struct model_layer layer_2 __read_mostly = {
    .uuid = 2,
    .input_size = 8,
    .output_size = 1,
    .comp_func = fc_2_comp,
};
/************************************ End Layer 2 ************************************/

/************************************** Layer 3 **************************************/
static void dequan_3_comp (s64 *input, s64 *output)
{
    // Q_min: 0.0
    // Q_max: 30.02955436706543
    
    output[0] = (input[0] + 128) * 30 / 255 + 0;
    
}

struct model_layer layer_3 __read_mostly = {
    .uuid = 3,
    .input_size = 1,
    .output_size = 1,
    .comp_func = dequan_3_comp,
};
/************************************ End Layer 3 ************************************/


/************************************** Model  **************************************/

struct model_container model_2333 __read_mostly = {
    .uuid = 2333,
    .input_size = 4,
    .output_size = 1,
};


/******************************************** Test Mode ********************************************/
struct app app = {
    .appid = 1,
    .input_size = 4,
    .output_size = 1,
};

/**************************************** End Test Mode ********************************************/


static int
__init liteflow_2333_model_init(void)
{
    
    s64 _input[4];
    s64 _output[1];
    int _output_pos;
    

    // Construct layers
    INIT_LIST_HEAD(&model_2333.layers);
    list_add(&layer_0.list, &model_2333.layers);
    list_add(&layer_1.list, &layer_0.list);
    list_add(&layer_2.list, &layer_1.list);
    list_add(&layer_3.list, &layer_2.list);

    
    // Test mode = on
    lf_register_app(&app);
    
    
    lf_register_model(1, &model_2333);

    
    lf_activate_model(1, 2333);
    
    // TODO
    _input[0] = 10 ;
    _input[1] = 20 ;
    _input[2] = 30 ;
    _input[3] = 40 ;

    lf_query_model(1, _input, _output);

    for (_output_pos = 0; _output_pos < 1; ++_output_pos) {
        printk(KERN_INFO "Output_%d: %lld\n", _output_pos, _output[_output_pos]);
    }
    

    return 0;
}

static void
__exit liteflow_2333_model_exit(void)
{
    lf_unregister_model(1, 2333);

    
    // Test mode = on
    lf_unregister_app(1);
    
}

module_init(liteflow_2333_model_init);
module_exit(liteflow_2333_model_exit);

MODULE_DESCRIPTION("liteflow 2333 model");
MODULE_AUTHOR("liteflow");
MODULE_LICENSE("GPL v2");

/************************************ End Model  ************************************/