/****************** main.c for model 1 generated by nn-loader.py *******************/
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/version.h>
#include <linux/slab.h>

#include "linux/liteflow.h"


/************************************** Layer 0 **************************************/
static void quan_0_comp (s64 *input, s64 *output)
{
    // Q_min: 0.0
    // Q_max: 62.0
    
    output[0] = (((s8)input[0] - 0) * 255 / (62 - 0) - 128);
    
    output[1] = (((s8)input[1] - 0) * 255 / (62 - 0) - 128);
    
    output[2] = (((s8)input[2] - 0) * 255 / (62 - 0) - 128);
    
    output[3] = (((s8)input[3] - 0) * 255 / (62 - 0) - 128);
    
}

struct model_layer layer_0 __read_mostly = {
    .uuid = 0,
    .input_size = 4,
    .output_size = 4,
    .comp_func = quan_0_comp,
};
/************************************ End Layer 0 ************************************/

/************************************** Layer 1 **************************************/
static void fc_1_comp (s64 *input, s64 *output)
{
    
    output[0] = ((s8)input[0] * -2 + (s8)input[1] * 33 + (s8)input[2] * 68 + (s8)input[3] * 7+  219);
    
    output[1] = ((s8)input[0] * -87 + (s8)input[1] * 71 + (s8)input[2] * 91 + (s8)input[3] * -15+  254);
    
    output[2] = ((s8)input[0] * 117 + (s8)input[1] * 36 + (s8)input[2] * -113 + (s8)input[3] * 31+  255);
    
    output[3] = ((s8)input[0] * -74 + (s8)input[1] * -88 + (s8)input[2] * -29 + (s8)input[3] * -21+  255);
    
    output[4] = ((s8)input[0] * 50 + (s8)input[1] * 27 + (s8)input[2] * -61 + (s8)input[3] * 24+  58);
    
    output[5] = ((s8)input[0] * -90 + (s8)input[1] * 86 + (s8)input[2] * 85 + (s8)input[3] * -127+  255);
    
    output[6] = ((s8)input[0] * 49 + (s8)input[1] * 23 + (s8)input[2] * 97 + (s8)input[3] * 34+  255);
    
    output[7] = ((s8)input[0] * -64 + (s8)input[1] * 24 + (s8)input[2] * 6 + (s8)input[3] * 98+  255);
    
}

struct model_layer layer_1 __read_mostly = {
    .uuid = 1,
    .input_size = 4,
    .output_size = 8,
    .comp_func = fc_1_comp,
};
/************************************ End Layer 1 ************************************/

/************************************** Layer 2 **************************************/
static void fc_2_comp (s64 *input, s64 *output)
{
    
    output[0] = ((s8)input[0] * 70 + (s8)input[1] * 17 + (s8)input[2] * 122 + (s8)input[3] * -50 + (s8)input[4] * -54 + (s8)input[5] * -127 + (s8)input[6] * -62 + (s8)input[7] * -14+  141);
    
}

struct model_layer layer_2 __read_mostly = {
    .uuid = 2,
    .input_size = 8,
    .output_size = 1,
    .comp_func = fc_2_comp,
};
/************************************ End Layer 2 ************************************/

/************************************** Layer 3 **************************************/
static void dequan_3_comp (s64 *input, s64 *output)
{
    // Q_min: 0.0
    // Q_max: 30.034034729003906
    
    output[0] = ( ((s8)input[0] + 128) * 30 / 255 + 0); 
    
}

struct model_layer layer_3 __read_mostly = {
    .uuid = 3,
    .input_size = 1,
    .output_size = 1,
    .comp_func = dequan_3_comp,
};
/************************************ End Layer 3 ************************************/


/************************************** Model  **************************************/

struct model_container model_1 __read_mostly = {
    .uuid = 1,
    .input_size = 4,
    .output_size = 1,
};


/******************************************** Test Mode ********************************************/
struct app app = {
    .appid = 1,
    .input_size = 4,
    .output_size = 1,
};

/**************************************** End Test Mode ********************************************/


static int
__init liteflow_1_model_init(void)
{
    
    s64 _input[4];
    s64 _output[1];
    int _output_pos;
    

    // Construct layers
    INIT_LIST_HEAD(&model_1.layers);
    list_add(&layer_0.list, &model_1.layers);
    list_add(&layer_1.list, &layer_0.list);
    list_add(&layer_2.list, &layer_1.list);
    list_add(&layer_3.list, &layer_2.list);

    
    // Test mode = on
    lf_register_app(&app);
    
    
    lf_register_model(1, &model_1);

    
    lf_activate_model(1, 1);
    // TODO
    
    _input[0] = 10 ;
    _input[1] = 20 ;
    _input[2] = 30 ;
    _input[3] = 40 ;

    lf_query_model(1, _input, _output);

    for (_output_pos = 0; _output_pos < 1; ++_output_pos) {
        printk(KERN_INFO "Output_%d: %lld\n", _output_pos, _output[_output_pos]);
    }
    

    return 0;
}

static void
__exit liteflow_1_model_exit(void)
{
    lf_unregister_model(1, 1);

    
    // Test mode = on
    lf_unregister_app(1);
    
}

module_init(liteflow_1_model_init);
module_exit(liteflow_1_model_exit);

MODULE_DESCRIPTION("liteflow 1 model");
MODULE_AUTHOR("liteflow");
MODULE_LICENSE("GPL v2");

/************************************ End Model  ************************************/
